package com.thecodevillage.remindme;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.thecodevillage.remindme.TodoItem;

import com.thecodevillage.remindme.TodoItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig todoItemDaoConfig;

    private final TodoItemDao todoItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        todoItemDaoConfig = daoConfigMap.get(TodoItemDao.class).clone();
        todoItemDaoConfig.initIdentityScope(type);

        todoItemDao = new TodoItemDao(todoItemDaoConfig, this);

        registerDao(TodoItem.class, todoItemDao);
    }
    
    public void clear() {
        todoItemDaoConfig.clearIdentityScope();
    }

    public TodoItemDao getTodoItemDao() {
        return todoItemDao;
    }

}
